# Generated by Django 4.1.4 on 2023-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('partner', models.CharField(default='', max_length=50)),
                ('percentage', models.IntegerField(default='')),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
