# Generated by Django 4.1.4 on 2023-04-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculations',
            new_name='Calculation',
        ),
    ]
